### ISSUE TITLE
IDE 2.0 compilation problem

### ISSUE THREAD

**Issue by murty206** [EnviroDIY/Arduino-SDI-12#81]
Hello I have started to use Arduino IDE 2.0 Beta but I get compilation errors below, I have tried to compile with Arduino IDE 1.8.13 I get no errors for compilation. What could be the problem?

Thanks in advance,

SDI12.cpp:139:35: error: 'TICKS_PER_BIT' was not declared in this scope  static const uint8_t txBitWidth = TICKS_PER_BIT;
SDI12.cpp:140:38: error: 'RX_WINDOW_FUDGE' was not declared in this scope  static const uint8_t rxWindowWidth = RX_WINDOW_FUDGE;  // A fudge factor to make things work
SDI12.cpp:141:40: error: 'BITS_PER_TICK_Q10' was not declared in this scope
 static const uint8_t bitsPerTick_Q10 = BITS_PER_TICK_Q10;
                                        ^~~~~~~~~~~~~~~~~
SDI12.cpp: In member function 'void SDI12::begin()':
SDI12.cpp:433:3: error: 'configSDI12TimerPrescale' was not declared in this scope
   configSDI12TimerPrescale();
   ^~~~~~~~~~~~~~~~~~~~~~~~
SDI12.cpp: In member function 'void SDI12::end()':
SDI12.cpp:446:3: error: 'resetSDI12TimerPrescale' was not declared in this scope
   resetSDI12TimerPrescale();
   ^~~~~~~~~~~~~~~~~~~~~~~
SDI12.cpp: At global scope:
SDI12.cpp:150:17: warning: 'uint16_t mul8x8to16(uint8_t, uint8_t)' defined but not used [-Wunused-function]
 static uint16_t mul8x8to16(uint8_t x, uint8_t y)

**Comment by SRGDamia1** [comment]
Have you been able to resolve this?  Can this issue be closed?
